Added the ability to add custom extension functions to the VariableDictionary
OctopusDeploy/Octostache pull request #55
Opened 2021-03-22 03:08 UTC by dkarzon

Building off the functionality used for the BuiltInFunctions this lets you add your own custom functions to the Octostache expressions without needing to fork the library yourself.

Useful for domain specific logic that falls outside of the current function selection. (See test cases for usage)

Not entirely sure on the approach to get the Extensions dictionary from the VariableDictionary instance to the TemplateEvaluator so let me know if there is a more preferable approach.

2021-03-22 03:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OctopusDeploy/Octostache?pullRequest=55) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OctopusDeploy/Octostache?pullRequest=55) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OctopusDeploy/Octostache?pullRequest=55) it.</sub>

2021-04-09 04:28 UTC, dkarzon commented
@droyad @matt-richardson Any movement on this one? Would be great to be able to use the official release with these changes instead of building myself from a branch.

2021-07-01 00:42 UTC, dkarzon commented
Bump 👋

2022-01-17 00:46 UTC, dkarzon commented
Any chance this could get a look at?

2022-06-23 01:42 UTC, dkarzon commented
@mjhilton Any feedback on this one?

2022-06-23 07:18 UTC, mjhilton commented
Hey @dkarzon, thanks for your PR 🙂

Overall the idea looks good, and I like that you've handled potential conflict between BuiltInFunctions and Extensions added afterwards. Thankyou also for adding tests ✅

You might have seen I've been doing some spring cleaning in the repo related to our build and release pipelines lately; I still need to make a couple of modifications to be able to run the pipeline against your fork. I'll try to get that done in the next few days so we can get the PR green.

Once I've done that, I'll do a slightly more detailed review, but I don't anticipate any major changes.

2022-06-27 05:26 UTC, mjhilton requested changes
Hi @dkarzon, I've run the build for your PR. The failed component was the `Enforce Code Style` stage, which failed with the following:

```
[14:51:53 ] Pending cleanups found in the following files:
[14:51:53 ]     M source/Octostache.Tests/ExtensionFixture.cs
[14:51:53 ]     M source/Octostache/Templates/EvaluationContext.cs
[14:51:53 ]     M source/Octostache/Templates/TemplateEvaluator.cs
[14:51:53 ]     M source/Octostache/VariableDictionary.cs
[14:51:53 ] Code Cleanups found
[14:51:53 ] Please run ReSharper Cleanup on your branch
```

You'll [need to run Code Cleanup locally](https://github.com/OctopusDeploy/Octostache#code-cleanup) on your branch to get it 🟢.

([Here's the `git diff`](https://github.com/OctopusDeploy/Octostache/files/8988805/gitdiff.txt) generated on the build server as a result, which is what you should end up with when you run the cleanup tool)

2022-06-27 05:26 UTC, mjhilton commented on source/Octostache/VariableDictionary.cs
> +            // Naming conflicts with BuiltInFunctions?
This has been handled in `TemplateEvaluator`, so I don't think we need this comment any more

2022-06-27 09:06 UTC, dkarzon commented
Thanks for the review @mjhilton I have run the code cleanup tool now. It picked up a lot of code changes unrelated to this PR which I have ignored for now and only included the files mentioned above.

2022-06-27 23:25 UTC, merged

2022-06-28 01:20 UTC, mjhilton commented
The next version of Octostache as a result of this change is `3.1.0`. It has been built and published to our internal staging NuGet feed.

We have an extensive suite of integration and acceptance tests in Octopus Server that indirectly exercise Octostache. 

I've raised the PR to bump the version of Octostache in Octopus Server. Once that pipeline goes 💚, I'll approve the promotion of the new `3.1.0` to `nuget.org` and it will be available for you. Thanks for your contribution @dkarzon :)

2022-06-28 01:44 UTC, dkarzon commented
Awesome! Thanks @mjhilton for your help 👍

2022-06-28 06:16 UTC, mjhilton commented
🚀 [3.1.0 has been published to NuGet](https://www.nuget.org/packages/Octostache)