Put quotes back in around string equality comparison
OctopusDeploy/Octostache pull request #61
Opened 2021-08-10 01:42 UTC by egorpavlikhin

### Background
When parsing a template with `TemplateParser.ParseTemplate(inputs);` we expect the result of parsing to be equivalent to the unparsed string. That is to say, there should be a way to translate parsed expression back to the original. I have discovered that this doesn't work with conditional string tokens, as `ConditionalStringExpressionToken.ToString()` does not put quotes around the right side of the equation.

This is particularly handy because we would like to evaluate all variables that are passed to new step packages and json escape the resulting values:
```csharp
var template = TemplateParser.ParseTemplate(jsonInputs);
jsonInputs = template.ToString();
foreach (var templateToken in template.Tokens)
{
    var arguments = templateToken.GetArguments();
    if (!arguments.Any()) continue; // to avoid TextToken, which doesn't need to be evaluated
    string evaluated = variables.Evaluate(templateToken.ToString());
    jsonInputs = jsonInputs.Replace($"\"{templateToken.ToString()}\"", JsonConvert.ToString(evaluated));
}
```
The above works, except when there is string comparison: `#{if Octopus.Environment.Name == \"Production\"}#{TestVariable}#{/if}`

### Change
This PR simply adds quotes to `ConditionalStringExpressionToken.ToString()` so that ConditionalToken can be resolved back to the original expression if needed.

### How to review
Perhaps there is a better way to parse and json escape all variables, in which case this change is not needed. Looking for suggestions.

2021-08-10 04:41 UTC, uglybugger requested changes
While I don't know enough to assess the correctness of the change, this is something I'd very much like to see a test around.

2021-08-10 04:48 UTC, egorpavlikhin commented
> While I don't know enough to assess the correctness of the change, this is something I'd very much like to see a test around.

Writing this so it's clear more background is needed: the question for me is who is using that function besides myself and what is useful to test.

2021-08-10 07:21 UTC, egorpavlikhin commented
I've added a test to check that a parsed template is converted back to an equivalent string. Hopefully, these are all the cases we need to cover. `#{if test}#{/if}` conversion to `#{if test}#{else}#{/if}` that happens in our tokens if not important, as the two expressions are evaluated to the same value (as opposed to the quotes example that I am fixing here, which is not equivalent).

2021-08-11 00:52 UTC, zentron requested changes
Awaiting corresponding changes on other areas e.g "filters".

2021-08-11 03:28 UTC, zentron approved these changes
Minor suggestion around test but I wouldn't consider it a blocker 👍

2021-08-11 03:28 UTC, zentron commented on source/Octostache.Tests/ParserFixture.cs
> +            TemplateParser.TryParseTemplate(template, out var parsedTemplate, out string error).Should().BeTrue();
My only comment here would be if we can split out the whole "if evaluation is true, the `parsedTemplate` should not be nulll and `error` should be null" into its own test, then make this test all about just the template check. Then add an extra comment, even a 1-liner, just to better explain why its doing this the replace on each value to end up with empty.

Ultimately nothing I'd consider a blocker, so feel free to merge before or after any tidy up.

2021-08-11 03:36 UTC, merged