Enable function calls in #{if} expressions
OctopusDeploy/Octostache pull request #83
Opened 2022-07-06 00:45 UTC by YihaoOct

## Background

The PR addresses #65.

Previously, for `#{if}` and `#{unless}` statements, we supported three types of expressions to be used as the condition:
1. `#{if <token>} ... #{/if}` where we test whether the value of `<token>` itself is falsy (i.e. "0", "no" or "false");
2. `#{if <token> == "string"} ... #{/if}` where the value of `<token>` is compared against a string. In this case, the string must appear on the right hand side of comparison;
3. `#{if <token1> == <token2>}` where 2 tokens are compared.

The `<token>`s here must be either a variable name (e.g. `Octopus.Web.BaseUrl`), or a variable name combined with indexers (`[ ... ]`) and properties accesses (`.`) (e.g. `Octopus.Action.Package[array[foo].containers[0].container].Registry`).

However, function calls (`|`) which are supported in normal substitutions (e.g. `#{Name | ToUpper}`) are not supported in `#{if}` statements. As a result, the users cannot write things like 
- `#{if MyVar | Trim == ""}`, 
- `#{if ProjectName | ToLower | Contains "octopus"}` 
and so on which would make their template much more succinct.

## Results
This PR adds supports to these use cases. Now, in addition to the originally allowed syntax, the user can also use functions in conditionals:

- `#{if ProjectName | ToLower | Contains "octopus"}` - use functions directly;
- `#{if ProjectName | ToLower == "MyProject"}` - use functions to compare against a string;
- `#{if "MyProject" == ProjectName | ToLower | Trim}` - string can appear on the left hand side as well, useful if the chained function calls become very long;
- `#{if ProjectName | ToLower | Trim == DefaultProjectName | ToLower | Trim}` - functions are supported on both sides of the comparison.

## Limitations
These use cases are NOT supported:
- `#{if "hello" == "hello"}` - compare string to string, because this is unnecessary since the result of the condition is already known
- `#{if "false"}` - directly use a string as the condition, because this is unnecessary
- `#{if "MyProject" | ToLower | EndsWith "project"}` - function calls on a string value, because the result is known
- `#{if ProjectName | ToUpper | Contains (DefaultProjectName | ToUpper)}` - associate the function call from the right hand side. The brackets are not supported, and a chained function call expression is always evaluated from left to right. So the only supported syntax is `#{if ProjectName | ToUpper | Contains DefaultProjectName | ToUpper}` (without brackets), which will be evaluated in the order of `((ProjectName | ToUpper) | Contains DefaultProjectName) | ToUpper` (which may evaluate to `"TRUE"` or `"FALSE"`). This is consistent with the current behaviour of function calls when used in normal substitutions.

2022-07-06 04:44 UTC, YihaoOct commented
Update to the last point above: actually we can use `#{if ProjectName | ToUpper | Contains #{DefaultProjectName | ToUpper}}` to change the order of binding, instead of using brackets. So the last limitation there doesn't actually exist.

2022-07-07 07:14 UTC, mjhilton requested changes
Overall this looks great, and the complexity of the parsing is a lot to fit in my head, but I trust both that you've done a thorough look at it, and that our tests will cover us for all core scenarios.

Two things that I'd like to see:
* There's a fixture called `UsageFixture` which the README points to, which is intended to document the usage of Octostache. It hasn't been consistently updated over the years, but I think in this case, we should make an effort to update it.
* I think somewhere (probably in Readme), giving some clear guidance about the way that chained function grouping works would be very helpful
  * I think it would also help if we encourage people toward using sub-expressions to make their templates readable rather than just relying on the inbuilt grouping, particularly with chained expressions in conditionals and iterators

So the only changes I'm requesting here are documentation changes. Other than that, I can't see any problems - looks back-compat to me.

2022-07-08 05:24 UTC, YihaoOct commented
I've added use cases for conditionals to the usage fixture. Looks like the most detailed documentation about the syntax is on our [documentation website](https://octopus.com/docs/projects/variables) which is also referenced in README. I will update that doco to include filters for conditionals, and also add some examples to show how to change the order of association of filter functions later.

2022-07-18 01:22 UTC, mjhilton approved these changes
Thanks for those updates to the `UsageFixture`, that will help people in future.

Let's ship it!

2022-07-18 03:01 UTC, merged